/* Trigger pour vérifier qu'il reste bien des chambres disponibles avant de réserver */
DELIMITER $$
CREATE OR REPLACE TRIGGER CHECK_ROOM_AVAILABILITY
BEFORE INSERT ON RESERVATIONS
FOR EACH ROW
BEGIN
DECLARE N INTEGER;
SELECT 1 INTO N FROM ROOMS RO
  WHERE RO.HOTEL_ID=NEW.HOTEL_ID AND RO.ROOMTYPE_ID=NEW.ROOMTYPE_ID
  AND RO.ID NOT IN (
    SELECT DISTINCT OC.ROOM_ID FROM RESERVATIONS RE
    LEFT JOIN OCCUPATIONS OC ON RE.ID = OC.RESERVATION_ID
    WHERE DATE(arrival_date) >= RE.ARRIVAL_DATE AND DATE(exit_date) <= RE.EXIT_DATE);
IF (N < NEW.ROOM_COUNT) THEN SIGNAL SQLSTATE '20000' SET MESSAGE_TEXT = 'NO_ROOM_AVAILABLE';
END IF;
END;
$$