/* Trigger pour vérifier si le client n'a pas déjà réservé un séjour dont les dates se chevauchent */
DELIMITER $$
CREATE OR REPLACE TRIGGER CHECK_RESERVATIONS_DATES
BEFORE INSERT ON RESERVATIONS
FOR EACH ROW
BEGIN
DECLARE N INTEGER;
SELECT 1 INTO N FROM RESERVATIONS
WHERE CLIENT_ID = NEW.CLIENT_ID
AND NOT(DATEDIFF(NEW.EXIT_DATE, ARRIVAL_DATE) <= 0 OR DATEDIFF(NEW.ARRIVAL_DATE, EXIT_DATE) >= 0);
IF (N > 0) THEN SIGNAL SQLSTATE '20000' SET MESSAGE_TEXT = 'OVERLAPPING';
END IF;
END;
$$