/* Trigger qui gère les actions à effectuer après l'archivage d'une réservation */
DELIMITER $$
CREATE OR REPLACE TRIGGER ON_ARCHIVE_RESERVATION
AFTER UPDATE ON RESERVATIONS
FOR EACH ROW
BEGIN
IF (NEW.IS_ARCHIVED) THEN
	UPDATE OCCUPATIONS SET IS_ARCHIVED = 1, IS_CLIENT_PRESENT = 0 WHERE RESERVATION_ID = NEW.ID;
	INSERT INTO BILLS(RESERVATION_ID,CLIENT_ID,AMOUNT,IS_PAYED,IS_ARCHIVED) VALUES (NEW.ID,NEW.CLIENT_ID,0.0,0,0);
END IF;
END;
$$