/* Trigger qui gère les actions à effectuer après l'archivage d'une occupation */
DELIMITER $$
CREATE OR REPLACE TRIGGER ON_ARCHIVE_OCCUPATION
AFTER UPDATE ON OCCUPATIONS
FOR EACH ROW
BEGIN
IF (NEW.IS_ARCHIVED) THEN
	DELETE FROM OCCUPANTS WHERE OCCUPATION_ID = NEW.ID;
	UPDATE BILLEDSERVICES SET IS_ARCHIVED = 1 WHERE OCCUPATION_ID = NEW.ID;
END IF;
END;
$$